### ISSUE TITLE
Parametric dynamics not working?

### ISSUE THREAD

**Issue by adomahidi** [embotech/Y2F#6]
Added another example (examples/mpc_parametric_dynamics) that isn't working either. I must be doing something wrong...

**Comment by GianUlli** [comment]
Here, the problem is that Y2F (and FORCES) can only handle affine parameters. In the example, you have the equality constraint "X(:,2) == A*X(:,1) + B*U(:,1)". Both, A and X(:,1), are parameters. To solve this problem, you could introduce an additional variable x0 and add the constraint "X(:,1) == x0". Use x0 as parameter instead of X(:,1).

**Comment by adomahidi** [comment]
I see, that makes sense - I did that with the recent commit https://github.com/embotech/Y2F/commit/4233ba32f6c528d8fc8440172efa7ee331601fcb but it still doesn't work

**Comment by GianUlli** [comment]
Same problem as in issue #5. I fixed it with commit 95cdf34d107b2ffebdeb7d3f5d5be723cafdf1fd.
